### ISSUE TITLE
KNN

### ISSUE THREAD

**Issue by jS5t3r** [chawins/knn-defense#2]
I saw that you need labels per class. eg. for cifar10 the labels are  1, 2, ..., 10.

Can I adapt the KNN in a away that I have either adversarial and non-adverasiarl examples? In a way to downgrade it?

**Comment by chawins** [comment]
If I understand you correctly, you want to have a deep k-NN model that **detects** adversarial examples instead of the usual classification? (feel free to correct me if I misunderstood)

If so, then yes! This is certainly possible. You will have to modify some code such that the attack is dynamically and adaptively generated during the model training. If you want to simply load pre-generated adversarial examples, that's also possible, but I doubt the model will be robust against adaptive adversaries.

**Comment by jS5t3r** [comment]
Thanks. You answered my question.

**Comment by chawins** [comment]
Absolutely. Feel free to let me know if you have any other questions.
